workflows:
  android-release:
    name: DUT Campus Streak Android Release
    max_build_duration: 60

    environment:
      flutter: stable

      android_signing:
        - dut_campusstreak_release

    scripts:
      - name: Check Flutter environment
        script: |
          echo "===== FLUTTER VERSION ====="
          flutter --version
          echo "===== DART VERSION ====="
          dart --version
          echo "===== JAVA VERSION ====="
          java -version

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build signed Android App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab